server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbt?characterEncoding=utf-8&useSSL=false
    username: root
    password: 159951
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
debug: true